### ISSUE TITLE
Golden Enemies

### ISSUE THREAD

**Issue by AliciaSpinnet** [gadhagod/Hyrule-Compendium-API#23]
Hello, i'm sorry to bother you but i was simply wondering if the golden variants of the enemies would show up here, i have been searching for them and i cannot find them, are they simply not in the compendium in the main game? my apologies if so

**Comment by AliciaSpinnet** [comment]
as well as the silver-maned lynel, apologies for being annoying

**Comment by AliciaSpinnet** [comment]
nevermind on the silver lynel, it just had a different name than i expected

**Comment by gadhagod** [comment]
Thanks for this issue. The golden enemies are part of the DLC pack. Right now, they are not in the compendium because they override IDs of other entries. I plan on having DLC entries fully supported soon, and will mention this issue when I do.

Again, thanks for bringing this to my attention.

**Comment by AliciaSpinnet** [comment]
You're Welcome! :)

**Comment by gadhagod** [comment]
Hello @AliciaSpinnet. The DLC images have been added in https://github.com/gadhagod/Hyrule-Compendium-API/commit/ad69e0cf6d6c1e4584e385f7b696af4bcb383873, but only the ones in the Champion's Ballad DLC pack. I'll add the Trials of the Sword entries to [the project's roadmap](https://github.com/gadhagod/Hyrule-Compendium-API/projects/1), and will hopefully have this done soon.

**Comment by gadhagod** [comment]
I've added functionality to the API to retrieve Master Mode entries. Since these entries have affect the IDs of other entries, there is a separate endpoint for them. 

Retrieve all master mode entries: `https://botw-compendium.herokuapp.com/api/v2/master_mode`.
Retrieve a single master mode entry: `https://botw-compendium.herokuapp.com/api/v2/master_mode/entry/<name or ID>`

These endpoints are still unstable, as tests are not fully developed yet. I have not documented these endpoints yet.
