### ISSUE TITLE
Recipe list

### ISSUE THREAD

**Issue by dylantoporek** [gadhagod/Hyrule-Compendium-API#27]
Hi! Great work with this! I was wondering if you were planning on getting the images more standardized like the ones from https://zelda.fandom.com/wiki/Food#Breath_of_the_Wild. Also, do you have any plans for adding a recipe list?

**Comment by gadhagod** [comment]
Thanks for this issue @dylantoporek. 
I've started working on a recipe endpoint for the API because of high demand, and it's coming along well. Thanks for the suggestion!
Also, what do you mean by "more standardized"? All the images are of the same dimensions. Do you mean the file format?

**Comment by gadhagod** [comment]
I decided not to include this feature because of the inconsistency of the recipes in botw. I created this API for the compendium, which has specified fields in the game. However, many recipes that have ingredients that can be substituted for (for example, any kind of meat). This would make the schema for the response very complex, and usage very perplexing.
