### ISSUE TITLE
TOTK imgs returning server error

### ISSUE THREAD

**Issue by XavierLora** [gadhagod/Hyrule-Compendium-API#43]

**Comment by gadhagod** [comment]
Just saw this, thanks for letting me know. For some reason, the tests are [not catching this error](https://github.com/gadhagod/Hyrule-Compendium-API/actions). I'm taking a look right now.

**Comment by ManuelMunozDeFrutos** [comment]
Hello! I'm testing the API but TOTK Images don't work. Any issue?

**Comment by XavierLora** [comment]
It hasn't been fixed since the original comment, unsure what would need to go into fixing it. I started a new job around when I posted this but I can make time if there is a desire and @gadhagod wants to make it happen. No stress or worries either way!

**Comment by gadhagod** [comment]
Thanks for bringing this to my attention again @ManuelMunozDeFrutos. That endpoint should now be throwing a 501 Not Implemented error instead of an internal server error. This is the expected behaviour as TOTK images have not been added yet.

Congratulations on the new job @XavierLora! I'll try to revive this project in terms of development this summer (school ends in one day), and hope to have TOTK images up soon. I apologize for such a late response!
