### ISSUE TITLE
Problems with the hyphen of "non-food"

### ISSUE THREAD

**Issue by GuilhemDuval** [gadhagod/Hyrule-Compendium-API#8]
When I do a request, I can't retrieve the data of an entry who is in the category "non-food". The hyphen in the category create errors. I don't know how to fix it. I'm using JavaScript.

**Comment by gadhagod** [comment]
Hi @GuilhemDuval. Thanks for reporting this.
I have changed the key from `non-food` to `non_food`. To use the new changes, you will have to use `v2`, rather than `v1` in the base URL. 
I haven't yet documented it because I wish to handle the errors better. I will work on this in a few days, as I'm a little backed up right now. Thanks!
